'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronDown, CircleUserRound, FileText, LayoutDashboard, LoaderCircle, LogOut, Menu, Package, Search, Settings, ShoppingBag, Trophy, Users, X } from 'lucide-react';
import Link from 'next/link';
import { apiRequest } from '../lib/api';

type User = { id: string; email: string; firstName: string; lastName: string; role: 'fan' | 'editor' | 'admin' };
type Overview = { userCount: number; orderCount: number; pendingOrderCount: number; productCount: number; lowStockCount: number; grossMerchandiseValueCents: number };
type Order = { id: string; status: string; totalCents: number; customerName?: string; customerEmail?: string; itemCount: number };
type Product = { id: string; name: string; priceCents: number; stock: number };
type AdminResource = 'teams' | 'players' | 'news' | 'fixtures' | 'standings' | 'products' | 'gallery' | 'sponsors';
type AdminRecord = Record<string, string | number | boolean | null> & { id: string };
const managementAreas: { label: string; resource: AdminResource; fields: { key: string; label: string; type?: string }[] }[] = [
  { label: 'Teams', resource: 'teams', fields: [{key:'name',label:'Team name'},{key:'shortName',label:'Short name'},{key:'logoUrl',label:'Logo URL'}] },
  { label: 'Players', resource: 'players', fields: [{key:'teamId',label:'Team ID'},{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'slug',label:'Slug'},{key:'jerseyNumber',label:'Jersey number',type:'number'},{key:'position',label:'Position'},{key:'nationality',label:'Nationality'},{key:'bio',label:'Biography'},{key:'photoUrl',label:'Photo URL'}] },
  { label: 'News Articles', resource: 'news', fields: [{key:'title',label:'Title'},{key:'slug',label:'Slug'},{key:'excerpt',label:'Excerpt'},{key:'body',label:'Article body'},{key:'coverUrl',label:'Cover URL'},{key:'publishedAt',label:'Publish date',type:'datetime-local'}] },
  { label: 'Match Management', resource: 'fixtures', fields: [{key:'homeTeamId',label:'Home team ID'},{key:'awayTeamId',label:'Away team ID'},{key:'competition',label:'Competition'},{key:'venue',label:'Venue'},{key:'kickoffAt',label:'Kick-off',type:'datetime-local'},{key:'status',label:'Status'},{key:'homeScore',label:'Home score',type:'number'},{key:'awayScore',label:'Away score',type:'number'}] },
  { label: 'Standings', resource: 'standings', fields: [{key:'teamId',label:'Team ID'},{key:'competition',label:'Competition'},{key:'season',label:'Season'},{key:'position',label:'Position',type:'number'},{key:'played',label:'Played',type:'number'},{key:'won',label:'Won',type:'number'},{key:'drawn',label:'Drawn',type:'number'},{key:'lost',label:'Lost',type:'number'},{key:'goalsFor',label:'Goals for',type:'number'},{key:'goalsAgainst',label:'Goals against',type:'number'},{key:'points',label:'Points',type:'number'}] },
  { label: 'Products', resource: 'products', fields: [{key:'name',label:'Name'},{key:'slug',label:'Slug'},{key:'description',label:'Description'},{key:'category',label:'Category'},{key:'priceCents',label:'Price cents',type:'number'},{key:'stock',label:'Stock',type:'number'},{key:'imageUrl',label:'Image URL'}] },
  { label: 'Gallery', resource: 'gallery', fields: [{key:'title',label:'Title'},{key:'mediaType',label:'Media type'},{key:'mediaUrl',label:'Media URL'},{key:'thumbnailUrl',label:'Thumbnail URL'},{key:'publishedAt',label:'Publish date',type:'datetime-local'}] },
  { label: 'Sponsors', resource: 'sponsors', fields: [{key:'name',label:'Name'},{key:'logoUrl',label:'Logo URL'},{key:'websiteUrl',label:'Website URL'},{key:'tier',label:'Tier'},{key:'sortOrder',label:'Sort order',type:'number'}] }
];
const areas = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Teams', icon: Trophy }, { label: 'Players', icon: Trophy }, { label: 'News Articles', icon: FileText }, { label: 'Match Management', icon: CalendarDays }, { label: 'Standings', icon: LayoutDashboard }, { label: 'Products', icon: Package }, { label: 'Orders', icon: ShoppingBag }, { label: 'Users', icon: Users }, { label: 'Gallery', icon: FileText }, { label: 'Sponsors', icon: Users }
];
const initialOverview: Overview = { userCount: 0, orderCount: 0, pendingOrderCount: 0, productCount: 0, lowStockCount: 0, grossMerchandiseValueCents: 0 };

export default function AdminPage() {
  const [active, setActive] = useState('Overview');
  const [menu, setMenu] = useState(false);
  const [admin, setAdmin] = useState<User | null>(null);
  const [overview, setOverview] = useState(initialOverview);
  const [orders, setOrders] = useState<Order[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [access, setAccess] = useState<'loading' | 'ready' | 'signed-out' | 'forbidden' | 'error'>('loading');
  const [message, setMessage] = useState('');
  const [records, setRecords] = useState<AdminRecord[]>([]);
  const [editing, setEditing] = useState<AdminRecord | null>(null);
  const [formValues, setFormValues] = useState<Record<string, string | number>>({});
  useEffect(() => { apiRequest<User>('/api/v1/auth/me').then(result => {
    if (result.data.role !== 'admin') { setAccess('forbidden'); return; }
    setAdmin(result.data);
    return Promise.all([apiRequest<Overview>('/api/v1/admin/overview'), apiRequest<Order[]>('/api/v1/admin/orders'), apiRequest<User[]>('/api/v1/admin/users'), apiRequest<Product[]>('/api/v1/admin/products')]).then(([overviewResult, orderResult, userResult, productResult]) => { setOverview(overviewResult.data); setOrders(orderResult.data); setUsers(userResult.data); setProducts(productResult.data); setAccess('ready'); });
  }).catch(error => setAccess(error instanceof Error && error.message === 'Sign in is required.' ? 'signed-out' : 'error')); }, []);
  const logout = async () => { await apiRequest('/api/v1/auth/logout', { method: 'POST' }); window.location.assign(`${process.env.NEXT_PUBLIC_BASE_PATH ?? ''}/`); };
  const updateOrder = async (id: string, status: string) => { const result = await apiRequest<Order>(`/api/v1/admin/orders/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setOrders(current => current.map(item => item.id === id ? result.data : item)); setMessage('Order status updated.'); };
  const updateStock = async (id: string, stock: number) => { const result = await apiRequest<Product>(`/api/v1/admin/products/${id}/stock`, { method: 'PATCH', body: JSON.stringify({ stock }) }); setProducts(current => current.map(item => item.id === id ? result.data : item)); setMessage('Product stock updated.'); };
  const selectArea = async (label: string) => { setActive(label); setMenu(false); setEditing(null); setFormValues({}); const area = managementAreas.find(item => item.label === label); if (area) { const result = await apiRequest<AdminRecord[]>(`/api/v1/admin/resources/${area.resource}`); setRecords(result.data); } };
  const saveRecord = async () => { const area = managementAreas.find(item => item.label === active); if (!area) return; const payload = Object.fromEntries(area.fields.map(field => [field.key, field.type === 'number' ? Number(formValues[field.key] ?? 0) : formValues[field.key] ?? ''])); const path = editing ? `/api/v1/admin/resources/${area.resource}/${editing.id}` : `/api/v1/admin/resources/${area.resource}`; const result = await apiRequest<AdminRecord>(path, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); setRecords(current => editing ? current.map(item => item.id === editing.id ? result.data : item) : [result.data, ...current]); setEditing(null); setFormValues({}); setMessage(`${area.label} saved.`); };
  const removeRecord = async (record: AdminRecord) => { const area = managementAreas.find(item => item.label === active); if (!area || !window.confirm(`Delete this ${area.label.toLowerCase()} record?`)) return; await apiRequest(`/api/v1/admin/resources/${area.resource}/${record.id}`, { method: 'DELETE' }); setRecords(current => current.filter(item => item.id !== record.id)); setMessage('Record deleted.'); };
  if (access === 'loading') return <main className="admin-gate"><LoaderCircle className="spin"/><p>Checking administrator access…</p></main>;
  if (access !== 'ready' || !admin) return <main className="admin-gate"><h1>{access === 'forbidden' ? 'Administrator access only' : access === 'signed-out' ? 'Sign in required' : 'Admin service unavailable'}</h1><p>{access === 'forbidden' ? 'Your supporter account cannot access club management.' : 'Use an authorized administrator account to continue.'}</p><Link className="admin-export" href={access === 'forbidden' ? '/profile' : '/login'}>{access === 'forbidden' ? 'GO TO PROFILE' : 'ADMIN SIGN IN'}</Link></main>;
  const rows = orders.slice(0, 8);
  return <main className="admin-app">
    <aside className={`admin-sidebar ${menu ? 'open' : ''}`}><div className="admin-brand"><span className="crest">DU</span><strong>UNITED<br/><small>CONTROL ROOM</small></strong><button className="admin-close" aria-label="Close admin navigation" onClick={() => setMenu(false)}><X size={17}/></button></div><div className="admin-nav">{areas.map(({ label, icon: Icon }) => <button className={active === label ? 'selected' : ''} key={label} onClick={() => selectArea(label)}><Icon size={17}/><span>{label}</span></button>)}</div><button className="admin-settings" onClick={logout}><LogOut size={16}/> Sign out</button></aside>
    <section className="admin-main"><header className="admin-header"><button className="admin-menu" aria-label={menu ? 'Close admin navigation' : 'Open admin navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}><Menu size={20}/></button><div><span className="admin-kicker">DURBAN UNITED / {active.toUpperCase()}</span><h1>{active}</h1></div><div className="admin-user"><span><strong>{admin.firstName} {admin.lastName}</strong><small>Administrator</small></span><CircleUserRound size={30}/><ChevronDown size={14}/></div></header>{message && <p className="admin-feedback" role="status">{message}</p>}
      {active === 'Overview' ? <><div className="admin-actions"><Link href="/" className="back-link"><ArrowLeft size={15}/> View public site</Link></div><div className="stat-grid"><div><span>Gross merchandise value</span><strong>{money(overview.grossMerchandiseValueCents)}</strong><small>Paid and active orders</small></div><div><span>Active users</span><strong>{overview.userCount}</strong><small>Admin and supporters</small></div><div><span>Orders awaiting action</span><strong>{overview.pendingOrderCount}</strong><small>{overview.orderCount} orders total</small></div><div><span>Products</span><strong>{overview.productCount}</strong><small>{overview.lowStockCount} low stock</small></div></div><OrdersPanel rows={rows} onUpdate={updateOrder}/></> : active === 'Orders' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">SHOPPING MANAGEMENT</span><h2>All orders</h2></div></div><OrdersTable rows={orders} onUpdate={updateOrder}/></section> : active === 'Products' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">SHOPPING MANAGEMENT</span><h2>Products and stock</h2></div></div><div className="admin-card-list">{products.map(product => <div key={product.id}><span><b>{product.name}</b><small>{money(product.priceCents)}</small></span><label>Stock<input aria-label={`${product.name} stock`} type="number" min="0" defaultValue={product.stock} onBlur={event => updateStock(product.id, Number(event.target.value))}/></label></div>)}</div></section> : active === 'Users' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">ACCESS & COMMUNICATIONS</span><h2>Users</h2></div></div><div className="admin-card-list">{users.map(user => <div key={user.id}><span><b>{user.firstName} {user.lastName}</b><small>{user.email}</small></span><strong>{user.role}</strong><button className="admin-export" onClick={async () => { const title = window.prompt('Message title'); const body = title ? window.prompt('Message') : ''; if (title && body) { await apiRequest(`/api/v1/admin/users/${user.id}/notifications`, { method:'POST', body: JSON.stringify({ title, body }) }); setMessage('Communication sent to profile.'); } }}>MESSAGE</button></div>)}</div></section> : <ResourceManager active={active} records={records} editing={editing} formValues={formValues} onEdit={(record) => { setEditing(record); setFormValues(Object.fromEntries(Object.entries(record).filter((entry): entry is [string, string | number] => typeof entry[1] === 'string' || typeof entry[1] === 'number'))); }} onChange={(key,value) => setFormValues(current => ({...current,[key]:value}))} onSave={saveRecord} onCancel={() => {setEditing(null);setFormValues({});}} onDelete={removeRecord}/>}
    </section>
  </main>;
}
function OrdersPanel({ rows, onUpdate }: { rows: Order[]; onUpdate: (id: string, status: string) => void }) { return <div className="admin-columns admin-orders-overview"><section className="data-panel"><div className="panel-head"><div><span className="admin-kicker">COMMERCE</span><h2>Recent orders</h2></div></div><OrdersTable rows={rows} onUpdate={onUpdate}/></section><section className="data-panel activity"><div className="panel-head"><div><span className="admin-kicker">OPERATIONS</span><h2>Management coverage</h2></div><span className="live-dot">LIVE API</span></div><p><b>Orders</b><br/>Track and update fulfilment status.</p><p><b>Products</b><br/>Monitor catalogue stock levels.</p><p><b>Users</b><br/>Review authorized club accounts.</p></section></div>; }
function OrdersTable({ rows, onUpdate }: { rows: Order[]; onUpdate: (id: string, status: string) => void }) { return <div className="table-wrap" tabIndex={0} role="region" aria-label="Orders table, scroll horizontally for more columns"><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(order => <tr key={order.id}><td>#{order.id.slice(0, 8)}</td><td>{order.customerName ?? order.customerEmail ?? 'Supporter'}</td><td>{order.itemCount}</td><td>{money(order.totalCents)}</td><td><select aria-label={`Status for order ${order.id}`} value={order.status} onChange={event => onUpdate(order.id, event.target.value)}>{['pending','paid','processing','shipped','complete','cancelled'].map(status => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{rows.length === 0 && <p className="admin-empty-row">No orders yet.</p>}</div>; }
function money(cents: number) { return new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 }).format(cents / 100); }

function ResourceManager({ active, records, editing, formValues, onEdit, onChange, onSave, onCancel, onDelete }: { active:string; records:AdminRecord[]; editing:AdminRecord|null; formValues:Record<string,string|number>; onEdit:(record:AdminRecord)=>void; onChange:(key:string,value:string|number)=>void; onSave:()=>void; onCancel:()=>void; onDelete:(record:AdminRecord)=>void }) { const area=managementAreas.find(item=>item.label===active); if(!area) return <section className="empty-panel"><Search size={22}/><h2>Select a management area</h2></section>; return <section className="admin-resource-layout"><div className="data-panel"><div className="panel-head"><div><span className="admin-kicker">CONTENT MANAGEMENT</span><h2>{active}</h2></div><button className="admin-export" onClick={()=>{onCancel();}}>NEW RECORD</button></div><div className="admin-record-grid">{records.map(record=><article key={record.id}><b>{String(record.title ?? record.name ?? (`${record.firstName ?? ''} ${record.lastName ?? ''}`.trim() || record.id))}</b><small>{Object.entries(record).filter(([key])=>key!=='id').slice(0,4).map(([key,value])=>`${key}: ${String(value ?? '')}`).join(' · ')}</small><div><button onClick={()=>onEdit(record)}>Edit</button><button className="danger" onClick={()=>onDelete(record)}>Delete</button></div></article>)}</div></div><form className="admin-editor" onSubmit={event=>{event.preventDefault();onSave();}}><span className="admin-kicker">{editing?'EDIT':'CREATE'} {active.toUpperCase()}</span>{area.fields.map(field=><label key={field.key}>{field.label}<input type={field.type??'text'} value={String(formValues[field.key] ?? '')} onChange={event=>onChange(field.key,field.type==='number'?Number(event.target.value):event.target.value)} required /></label>)}<div><button className="admin-export" type="submit">SAVE</button>{editing&&<button type="button" onClick={onCancel}>CANCEL</button>}</div></form></section>; }
