'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronDown, CircleUserRound, FileText, LayoutDashboard, LoaderCircle, LogOut, Menu, Package, Search, Settings, ShoppingBag, Trophy, Users, X } from 'lucide-react';
import Link from 'next/link';
import { apiRequest } from '../lib/api';

type User = { id: string; email: string; firstName: string; lastName: string; role: 'fan' | 'editor' | 'admin' };
type Overview = { userCount: number; orderCount: number; pendingOrderCount: number; productCount: number; lowStockCount: number; grossMerchandiseValueCents: number };
type Order = { id: string; status: string; totalCents: number; customerName?: string; customerEmail?: string; itemCount: number };
type Product = { id: string; name: string; priceCents: number; stock: number };
const areas = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Products', icon: Package }, { label: 'Orders', icon: ShoppingBag }, { label: 'Users', icon: Users }, { label: 'Players', icon: Trophy }, { label: 'News Articles', icon: FileText }, { label: 'Match Management', icon: CalendarDays }
];
const initialOverview: Overview = { userCount: 0, orderCount: 0, pendingOrderCount: 0, productCount: 0, lowStockCount: 0, grossMerchandiseValueCents: 0 };

export default function AdminPage() {
  const [active, setActive] = useState('Overview');
  const [menu, setMenu] = useState(false);
  const [admin, setAdmin] = useState<User | null>(null);
  const [overview, setOverview] = useState(initialOverview);
  const [orders, setOrders] = useState<Order[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [access, setAccess] = useState<'loading' | 'ready' | 'signed-out' | 'forbidden' | 'error'>('loading');
  const [message, setMessage] = useState('');
  useEffect(() => { apiRequest<User>('/api/v1/auth/me').then(result => {
    if (result.data.role !== 'admin') { setAccess('forbidden'); return; }
    setAdmin(result.data);
    return Promise.all([apiRequest<Overview>('/api/v1/admin/overview'), apiRequest<Order[]>('/api/v1/admin/orders'), apiRequest<User[]>('/api/v1/admin/users'), apiRequest<Product[]>('/api/v1/admin/products')]).then(([overviewResult, orderResult, userResult, productResult]) => { setOverview(overviewResult.data); setOrders(orderResult.data); setUsers(userResult.data); setProducts(productResult.data); setAccess('ready'); });
  }).catch(error => setAccess(error instanceof Error && error.message === 'Sign in is required.' ? 'signed-out' : 'error')); }, []);
  const logout = async () => { await apiRequest('/api/v1/auth/logout', { method: 'POST' }); window.location.assign(`${process.env.NEXT_PUBLIC_BASE_PATH ?? ''}/`); };
  const updateOrder = async (id: string, status: string) => { const result = await apiRequest<Order>(`/api/v1/admin/orders/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setOrders(current => current.map(item => item.id === id ? result.data : item)); setMessage('Order status updated.'); };
  const updateStock = async (id: string, stock: number) => { const result = await apiRequest<Product>(`/api/v1/admin/products/${id}/stock`, { method: 'PATCH', body: JSON.stringify({ stock }) }); setProducts(current => current.map(item => item.id === id ? result.data : item)); setMessage('Product stock updated.'); };
  if (access === 'loading') return <main className="admin-gate"><LoaderCircle className="spin"/><p>Checking administrator access…</p></main>;
  if (access !== 'ready' || !admin) return <main className="admin-gate"><h1>{access === 'forbidden' ? 'Administrator access only' : access === 'signed-out' ? 'Sign in required' : 'Admin service unavailable'}</h1><p>{access === 'forbidden' ? 'Your supporter account cannot access club management.' : 'Use an authorized administrator account to continue.'}</p><Link className="admin-export" href={access === 'forbidden' ? '/profile' : '/login'}>{access === 'forbidden' ? 'GO TO PROFILE' : 'ADMIN SIGN IN'}</Link></main>;
  const rows = orders.slice(0, 8);
  return <main className="admin-app">
    <aside className={`admin-sidebar ${menu ? 'open' : ''}`}><div className="admin-brand"><span className="crest">DU</span><strong>UNITED<br/><small>CONTROL ROOM</small></strong><button className="admin-close" aria-label="Close admin navigation" onClick={() => setMenu(false)}><X size={17}/></button></div><div className="admin-nav">{areas.map(({ label, icon: Icon }) => <button className={active === label ? 'selected' : ''} key={label} onClick={() => { setActive(label); setMenu(false); }}><Icon size={17}/><span>{label}</span></button>)}</div><button className="admin-settings" onClick={logout}><LogOut size={16}/> Sign out</button></aside>
    <section className="admin-main"><header className="admin-header"><button className="admin-menu" aria-label={menu ? 'Close admin navigation' : 'Open admin navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}><Menu size={20}/></button><div><span className="admin-kicker">DURBAN UNITED / {active.toUpperCase()}</span><h1>{active}</h1></div><div className="admin-user"><span><strong>{admin.firstName} {admin.lastName}</strong><small>Administrator</small></span><CircleUserRound size={30}/><ChevronDown size={14}/></div></header>{message && <p className="admin-feedback" role="status">{message}</p>}
      {active === 'Overview' ? <><div className="admin-actions"><Link href="/" className="back-link"><ArrowLeft size={15}/> View public site</Link></div><div className="stat-grid"><div><span>Gross merchandise value</span><strong>{money(overview.grossMerchandiseValueCents)}</strong><small>Paid and active orders</small></div><div><span>Active users</span><strong>{overview.userCount}</strong><small>Admin and supporters</small></div><div><span>Orders awaiting action</span><strong>{overview.pendingOrderCount}</strong><small>{overview.orderCount} orders total</small></div><div><span>Products</span><strong>{overview.productCount}</strong><small>{overview.lowStockCount} low stock</small></div></div><OrdersPanel rows={rows} onUpdate={updateOrder}/></> : active === 'Orders' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">SHOPPING MANAGEMENT</span><h2>All orders</h2></div></div><OrdersTable rows={orders} onUpdate={updateOrder}/></section> : active === 'Products' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">SHOPPING MANAGEMENT</span><h2>Products and stock</h2></div></div><div className="admin-card-list">{products.map(product => <div key={product.id}><span><b>{product.name}</b><small>{money(product.priceCents)}</small></span><label>Stock<input aria-label={`${product.name} stock`} type="number" min="0" defaultValue={product.stock} onBlur={event => updateStock(product.id, Number(event.target.value))}/></label></div>)}</div></section> : active === 'Users' ? <section className="data-panel admin-wide-panel"><div className="panel-head"><div><span className="admin-kicker">ACCESS</span><h2>Users</h2></div></div><div className="admin-card-list">{users.map(user => <div key={user.id}><span><b>{user.firstName} {user.lastName}</b><small>{user.email}</small></span><strong>{user.role}</strong></div>)}</div></section> : <section className="empty-panel"><div className="empty-icon"><Search size={22}/></div><span className="admin-kicker">{active.toUpperCase()}</span><h2>Manage {active.toLowerCase()}</h2><p>This role-protected workspace is connected to the live API; detailed editing is the next module.</p></section>}
    </section>
  </main>;
}
function OrdersPanel({ rows, onUpdate }: { rows: Order[]; onUpdate: (id: string, status: string) => void }) { return <div className="admin-columns admin-orders-overview"><section className="data-panel"><div className="panel-head"><div><span className="admin-kicker">COMMERCE</span><h2>Recent orders</h2></div></div><OrdersTable rows={rows} onUpdate={onUpdate}/></section><section className="data-panel activity"><div className="panel-head"><div><span className="admin-kicker">OPERATIONS</span><h2>Management coverage</h2></div><span className="live-dot">LIVE API</span></div><p><b>Orders</b><br/>Track and update fulfilment status.</p><p><b>Products</b><br/>Monitor catalogue stock levels.</p><p><b>Users</b><br/>Review authorized club accounts.</p></section></div>; }
function OrdersTable({ rows, onUpdate }: { rows: Order[]; onUpdate: (id: string, status: string) => void }) { return <div className="table-wrap" tabIndex={0} role="region" aria-label="Orders table, scroll horizontally for more columns"><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(order => <tr key={order.id}><td>#{order.id.slice(0, 8)}</td><td>{order.customerName ?? order.customerEmail ?? 'Supporter'}</td><td>{order.itemCount}</td><td>{money(order.totalCents)}</td><td><select aria-label={`Status for order ${order.id}`} value={order.status} onChange={event => onUpdate(order.id, event.target.value)}>{['pending','paid','processing','shipped','complete','cancelled'].map(status => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{rows.length === 0 && <p className="admin-empty-row">No orders yet.</p>}</div>; }
function money(cents: number) { return new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 }).format(cents / 100); }
