'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Bell, Bot, CalendarDays, ChevronRight, CircleUserRound, Heart, Menu, Sparkles, Ticket, Trophy, X } from 'lucide-react';
import { AnimatePresence, MotionConfig, motion } from 'framer-motion';

const navItems = ['Home', 'News', 'Match Centre', 'Squad', 'Gallery', 'Club History', 'Shop', 'Contact', 'Login / Register'];
const routeMap: Record<string, string> = { News: 'news', Fixtures: 'match-centre', Results: 'match-centre', 'Match Centre': 'match-centre', Squad: 'squad', Gallery: 'gallery', 'Club History': 'club-history', Shop: 'shop', Contact: 'contact', 'Login / Register': 'login' };
const players = [
  { name: 'Thabo Mokoena', pos: 'MIDFIELDER', no: '08', image: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=800&q=80' },
  { name: 'Siyanda Ndlovu', pos: 'FORWARD', no: '11', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80' },
  { name: 'Liam Jacobs', pos: 'GOALKEEPER', no: '01', image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=800&q=80' },
  { name: 'Bongani Cele', pos: 'DEFENDER', no: '04', image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=800&q=80' }
];
const news = [
  { title: 'A new chapter begins under the lights', type: 'CLUB NEWS', date: '06 SEP 2026', image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=80' },
  { title: 'Five things to know about the new season', type: 'FEATURE', date: '04 SEP 2026', image: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=800&q=80' },
  { title: 'United announce community football fund', type: 'COMMUNITY', date: '29 AUG 2026', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80' }
];
const products = [
  { name: 'Home Jersey 26/27', price: 'R899', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80' },
  { name: 'United Training Tee', price: 'R449', image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80' },
  { name: 'Heritage Cap', price: 'R299', image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=600&q=80' },
  { name: 'Matchday Scarf', price: 'R249', image: 'https://images.unsplash.com/photo-1607453998774-d533f65dac99?auto=format&fit=crop&w=600&q=80' }
];
const heroSlides = [
  { image: '/images/team-home-away.jpg', label: 'HOME & AWAY · 26/27' },
  { image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1800&q=85', label: 'UNITED UNDER THE LIGHTS' },
  { image: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1800&q=85', label: 'THE COAST. THE CLUB.' }
];
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] as const } } };
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.08 } } };

export default function Home() {
  const [active, setActive] = useState('Home');
  const [chatOpen, setChatOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [cart, setCart] = useState(0);
  const [notice, setNotice] = useState('');
  const [heroSlide, setHeroSlide] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setHeroSlide(current => (current + 1) % heroSlides.length), 5000); return () => window.clearInterval(timer); }, []);
  const moveHero = (direction: number) => setHeroSlide(current => (current + direction + heroSlides.length) % heroSlides.length);
  const select = (item: string) => { setActive(item); setMenuOpen(false); setNotice(''); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <MotionConfig reducedMotion="user"><main className="app">
    <header className="nav"><button className="brand" onClick={() => select('Home')} aria-label="Durban United home"><span className="crest">DU</span><span>DURBAN<br />UNITED</span></button><nav className="links" aria-label="Primary navigation">{navItems.map(item => item === 'Home' ? <button key={item} className={active === item ? 'active' : ''} onClick={() => select(item)}>{item}</button> : <Link key={item} href={`/${routeMap[item]}`}>{item}</Link>)}</nav><div className="nav-actions"><Link className="icon-btn" aria-label="Fan profile" href="/login"><CircleUserRound size={17} /></Link><button className="icon-btn mobile-menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(value => !value)}>{menuOpen ? <X size={18}/> : <Menu size={18}/>}</button></div></header>
    {menuOpen && <nav className="mobile-menu" aria-label="Mobile navigation">{navItems.map(item => item === 'Home' ? <button key={item} onClick={() => select(item)}>Home</button> : <Link key={item} href={`/${routeMap[item]}`}>{item}</Link>)}</nav>}
    {notice && <div className="ticker"><strong>{notice}</strong><button className="link" onClick={() => setNotice('')}>DISMISS</button></div>}
    <motion.section className="hero" initial="hidden" animate="visible" variants={stagger}><motion.div className="hero-content" variants={reveal}><div className="eyebrow">EST. 1976 · DURBAN, SOUTH AFRICA</div><h1>SELIVUTHIWE<br /><em>UPHUTHU.</em></h1><p className="hero-copy">One city. One badge. A new era of football is rising from the Indian Ocean.</p><div className="actions"><motion.button className="primary" whileHover={{ y: -3 }} whileTap={{ scale: .97 }} onClick={() => select('Match Centre')}>MATCH CENTRE <ArrowUpRight size={14} style={{verticalAlign:'middle'}} /></motion.button><motion.button className="secondary" whileHover={{ y: -3 }} whileTap={{ scale: .97 }} onClick={() => select('Club History')}>OUR STORY</motion.button></div></motion.div><motion.div className="hero-badge" variants={reveal}><div className="team-badge">DU</div><span>HOME KIT · 26/27</span></motion.div></motion.section>
    <div className="ticker"><strong>NEXT MATCH</strong><span className="dot" /><span>27 SEP · 15:00</span><span className="dot" /><span>MOSES MABHIDA STADIUM</span><span style={{marginLeft:'auto'}}>#UNITEDWE RISE</span></div>
    <motion.section className="section" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={reveal}><div className="section-head"><div><p>ON THE PITCH</p><h2>Matchday</h2></div><button className="link" onClick={() => select('Fixtures')}>ALL FIXTURES <ChevronRight size={13} style={{verticalAlign:'middle'}} /></button></div><div className="match-grid"><motion.div className="match-card next" whileHover={{ y: -5 }}><div className="match-top"><span>Betway Premiership · Round 04</span><span className="match-time">15:00</span></div><div className="teams"><div><div className="team-badge">DU</div><div className="team-name">DURBAN<br/>UNITED · HOME</div></div><div className="vs">VS</div><div><div className="team-badge away-badge">DU</div><div className="team-name">STELLENBOSCH<br/>FC · AWAY</div></div></div><div className="match-info"><span>Sun · 27 Sep 2026</span><span>Moses Mabhida Stadium</span></div></motion.div><motion.div className="match-card result" whileHover={{ y: -5 }}><div className="match-top"><span>LAST RESULT</span><span className="tag">FULL TIME</span></div><div className="teams"><div><div className="team-badge">DU</div><div className="team-name">DURBAN UNITED</div></div><div className="result-score">1 — 1</div><div><div className="team-badge away-badge">DU</div><div className="team-name">AMAZULU</div></div></div><div className="match-info"><span>20 Sep 2026</span><span>1 point secured</span></div></motion.div></div></motion.section>
    <motion.section className="section" style={{paddingTop:20}} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .15 }} variants={reveal}><div className="section-head"><div><p>FROM THE CLUB</p><h2>Latest stories</h2></div><button className="link" onClick={() => select('News')}>VIEW ALL NEWS <ChevronRight size={13} style={{verticalAlign:'middle'}} /></button></div><motion.div className="news-grid" variants={stagger}>{news.map((item, i) => <motion.article className={`news-card ${i===0?'featured':''}`} key={item.title} style={{backgroundImage:`url(${item.image})`}} variants={reveal} whileHover={{ scale: 1.02 }}><div className="news-body"><small>{item.date} · {item.type}</small><h3>{item.title}</h3></div></motion.article>)}</motion.div></motion.section>
    <motion.section className="section" style={{paddingTop:45}} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .15 }} variants={reveal}><div className="section-head"><div><p>MEET THE TEAM</p><h2>Our people</h2></div><button className="link" onClick={() => select('Squad')}>FULL SQUAD <ChevronRight size={13} style={{verticalAlign:'middle'}} /></button></div><motion.div className="players" variants={stagger}>{players.map(player => <motion.article className="player-card" key={player.name} variants={reveal} whileHover={{ y: -7 }}><img src={player.image} alt={player.name} /><div className="player-meta"><div><div className="player-name">{player.name}</div><span className="player-pos">{player.pos}</span></div><div className="number">{player.no}</div></div></motion.article>)}</motion.div></motion.section>
    <motion.section className="section store-band" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .15 }} variants={reveal}><div className="section-head"><div><p>THE UNITED STORE</p><h2>Wear the feeling.</h2></div><button className="link" onClick={() => select('Shop')}>SHOP ALL <ChevronRight size={13} style={{verticalAlign:'middle'}} /></button></div><motion.div className="shop-grid" variants={stagger}>{products.map(product => <motion.article className="shop-card" key={product.name} variants={reveal} whileHover={{ y: -7 }}><img src={product.image} alt={product.name} /><div className="shop-info"><div>{product.name}<small>Official collection</small></div><span>{product.price}</span></div><button className="primary" style={{width:'100%',marginTop:10}} onClick={() => {setCart(cart+1);setNotice(`${product.name} added to your bag.`)}}>ADD TO BAG</button></motion.article>)}</motion.div></motion.section>
    <section className="section"><div className="fan-strip"><div className="portal-card"><Sparkles size={22} color="var(--lime)" /><h2>Your club.<br />Your space.</h2><p>Join the United family for early ticket access, exclusive stories and rewards that bring you closer to the badge.</p><button className="primary" onClick={() => select('Login / Register')}>ENTER FAN HUB <ArrowUpRight size={14} style={{verticalAlign:'middle'}} /></button></div><div className="perks"><div className="perk"><Ticket size={19}/><strong>Priority access</strong><span>Never miss a home game.</span></div><div className="perk"><Heart size={19}/><strong>Save your favourites</strong><span>Build your club feed.</span></div><div className="perk"><Trophy size={19}/><strong>Earn rewards</strong><span>Every chant counts.</span></div><div className="perk"><CalendarDays size={19}/><strong>Matchday alerts</strong><span>Be there from kick-off.</span></div></div></div></section>
    <footer className="footer"><div className="brand"><span className="crest">DU</span><span>DURBAN UNITED</span></div><span>© 2026 Durban United Football Club</span><span>Privacy · Terms · Contact</span></footer>
    <button className="chat" aria-label={chatOpen ? 'Close fan assistant' : 'Open fan assistant'} aria-expanded={chatOpen} onClick={() => setChatOpen(!chatOpen)}>{chatOpen ? <X size={20}/> : <Bot size={21}/>}</button>{chatOpen && <div className="chat-panel"><h3>United assistant</h3><p>Ask me about fixtures, squad stats, news or finding the right matchday gear.</p><input aria-label="Ask the club assistant" placeholder="Ask the club anything..." onKeyDown={event => { if (event.key === 'Enter') setNotice('The club assistant will be available when the live service is connected.'); }} /></div>}
  </main></MotionConfig>;
}
